script: scripts/exp.py
config_name: pi05_libero_online_aw_sft
project_name: awr_sweep_batchsize_fix
group_name: awr_sweep
params:
  log_interval: [2000]
  lr_schedule.value: [2.5e-5]
  num_train_steps: [100000]
  overwrite: [True]

 
  rl.discount: [0.99]
  collect.collect_interval: [2000]
  collect.num_eval_rollouts: [8]
  collect.num_initial_rollouts: [0]
  collect.num_rollouts: [1]
  collect.use_time_to_success_as_reward: [True]
  !!python/tuple [collect.tasks, collect.eval_tasks]: [
      [libero_90_44, libero_90_44],     # "Turn on the stove"
      [libero_90_59, libero_90_59],     # "Pick up the tomato sauce and put it in the tray"
  ]

  rl.buffer_capacity: [250000]
  rl.critic.pre_training_steps: [900]
  rl.critic.num_updates_per_batch: [1]
  rl.crtic.batch_size: [1024]
  rl.online_ratio: [1.0]
  rl.policy.training_start_step: [900]
  rl.policy.update_interval: [1]
  rl.policy.reset_params_to_ema_period: [500]
  rl.store_success_episodes_only: [False]
  rl.critic.td_weight_schedule.switch_step: [1_000_000]
  rl.critic.td_weight_schedule.init_value: [1]
  rl.critic.td_weight_schedule.end_value: [1]
  rl.critic.use_ema: [True]
  rl.use_mc_returns: [False]
  rl.critic.use_bronet: [True]

  seed: [0, 1, 2]