script: scripts/exp.py
config_name: pi05_libero_online_aw_sft
project_name: awr_agent_sweep
group_name: awr_agent
params:
  overwrite: [True]
  seed: [0, 1, 2]
  batch_size: [256]
  num_train_steps: [5000]
  log_interval: [25]
  lr_schedule.value: [5e-5]
  collect.env_num: [1]
  collect.eval_env_num: [4]
  collect.eval_interval: [300]
  collect.collect_interval: [300]
  collect.num_rollouts: [1]
  collect.num_eval_rollouts: [32]
  collect.use_time_to_success_as_reward: [True]
  collect.num_initial_rollouts: [5]
  [collect.tasks, collect.eval_tasks]: [
    [libero_90_14, libero_90_14],
    [libero_90_59, libero_90_59],
    [libero_90_64, libero_90_64],
    [libero_90_82, libero_90_82],
  ]
  rl.policy_update_interval: [1]
  rl.buffer_capacity: [250000]
  rl.num_critic_updates_per_batch: [10]
  rl.policy_training_start_step: [900]
  rl.online_ratio: [1.0]
  rl.reset_policy_params_to_ema_period: [500]
  rl.use_mc_returns: [False]
  rl.td_weight_schedule.switch_step: [900]
  rl.store_success_episodes_only: [False]
  rl.num_offline_pretraining_steps: [1_000]
  rl.warm_start_critic_update_interval: [1]
