script: scripts/exp.py
config_name: pi05_libero_online_best_of_n
project_name: best_of_n_sweep
group_name: best_of_n_sweep
params:
  log_interval: [25]
  save_interval: [100000]
  num_train_steps: [100000]

  collect.collect_interval: [6000]
  collect.eval_interval: [10000]
  collect.num_rollouts: [10]
  collect.store_prefix_rep: [True]
  !!python/tuple [collect.tasks, collect.eval_tasks]: [
    [libero_90_44, libero_90_44],     # "Turn on the stove"
    [libero_90_59, libero_90_59],     # "Pick up the tomato sauce and put it in the tray"
  ]

  rl.buffer_capacity: [250000]
  rl.critic.inference_start_step: [0]
  rl.critic.pre_training_steps: [0]
  rl.critic.td_weight_schedule.init_value: [0.5]
  rl.critic.td_weight_schedule.end_value: [0.5]
  rl.critic.td_weight_schedule.switch_step: [500000]

  seed: [0, 1, 2]