script: scripts/exp.py
config_name: pi05_libero_online_best_of_n
project_name: value_learning
group_name: value_learning
params:
  overwrite: [True]
  seed: [0, 1, 2]
  log_interval: [25]
  batch_size: [256]
  num_train_steps: [100_010]
  save_interval: [100_000]

  collect.env_num: [4]
  collect.eval_env_num: [4]
  collect.eval_interval: [10000]
  collect.num_eval_rollouts: [32]
  collect.num_rollouts: [16]
  collect.collect_interval: [6000]
  collect.use_time_to_success_as_reward: [True]
  collect.store_prefix_rep: [True]
  !!python/tuple [collect.tasks, collect.eval_tasks]: [
    [libero_90_44, libero_90_44],     # "Turn on the stove"
    [libero_90_59, libero_90_59],     # "Pick up the tomato sauce and put it in the tray"
  ]

  rl.buffer_capacity: [250000]
  rl.num_critic_updates_per_batch: [1]
  rl.n_samples: [32]
  rl.critic_training_start_step: [0]
  rl.critic_inference_start_step: [9000]
  rl.num_offline_pretraining_steps: [0]
  rl.num_value_bins: [1]
  rl.value_target_type: [one_hot]
  rl.critic_encoder_type: [pi0_prefix]       # ["pi0_prefix", "resnet", "pi0_prefix_resnet"],
  rl.train_on_policy_value_function: [False]
  rl.discount: [0.99]
  rl.offline_buffer_load_paths: [/capstor/store/cscs/swissai/a143/project-vla-pt/libero-hf/libero_online_buffer_time_to_success]
  !!python/tuple [rl.td_weight_schedule.init_value, rl.td_weight_schedule.end_value, rl.td_weight_schedule.switch_step, rl.critic_pre_training_steps]: [
      [1.0, 1.0, 999999, 0],  # TD only
      [0.0, 1.0, 9000, 9000],       # MC-then-TD
      [0.5, 0.5, 500000, 0],  # 0.5*(MC+TD)
  ]
