script: scripts/exp.py
config_name: pi05_libero_online_best_of_n
project_name: best_of_n_config_fix
group_name: best_of_n_sweep
params:
  log_interval: [25]
  save_interval: [100000]
  num_train_steps: [100000]
  overwrite: [True]

  collect.collect_interval: [6000]
  collect.eval_interval: [10000]
  collect.num_rollouts: [10]
  collect.store_prefix_rep: [True]
  collect.use_time_to_success_as_reward: [True]
  !!python/tuple [collect.tasks, collect.eval_tasks]: [
    [libero_90_59, libero_90_59],
  ]

  batch_size: [1024]
  rl.discount: [0.995]
  rl.buffer_capacity: [250000]
  rl.critic.inference_start_step: [0]
  rl.critic.pre_training_steps: [0]
  rl.critic.td_weight_schedule.init_value: [0.5]
  rl.critic.td_weight_schedule.end_value: [0.5]
  rl.critic.td_weight_schedule.switch_step: [500000]
  rl.critic.use_bronet: [False]
  rl.critic.bronet_hidden_dim: [512]
  rl.n_samples: [32]

  seed: [0]