script: scripts/exp.py
config_name: pi05_libero_online_filtered_sft
project_name: filtered_sft_sweep
group_name: filtered_sft_sweep
params:
  log_interval: [25]
  lr_schedule.value: [2.5e-5]
  num_train_steps: [5_000]
  overwrite: [True]

  collect.collect_interval: [300]
  collect.env_num: [1]
  collect.num_initial_rollouts: [5]
  collect.num_rollouts: [1]

  rl.buffer_capacity: [250000]
  rl.online_ratio: [1.0]
  rl.policy_training_start_step: [900]
  rl.reset_policy_params_to_ema_period: [500]
  !!python/tuple [collect.tasks, collect.eval_tasks]: [
    [libero_90_14, libero_90_14],
    [libero_90_38, libero_90_38],
    [libero_90_59, libero_90_59],
    [libero_90_64, libero_90_64],
    [libero_90_82, libero_90_82],
  ]

  seed: [0, 1, 2]
