script: scripts/exp.py
config_name: pi05_libero_online_filtered_sft
project_name: filtered_sft_sweep
group_name: filtered_sft_sweep
params:
  log_interval: [25]
  lr_schedule.value: [2.5e-5]
  num_train_steps: [5_000]

  collect.collect_interval: [300]
  collect.num_eval_rollouts: [8]
  collect.num_initial_rollouts: [5]
  collect.num_rollouts: [1]
  !!python/tuple [collect.tasks, collect.eval_tasks]: [
    [libero_90_32-63, libero_90_32-63],
  ]

  rl.buffer_capacity: [250000]
  rl.online_ratio: [1.0]

  seed: [0, 1, 2]