script: scripts/exp.py
config_name: pi05_molmo_online_aw_sft_expert_only
project_name: vla-post-training
group_name: multitask_tasks1_bofn_plus_fsft_eo_molmo_v0_seed1
params:
  log_interval: [25]
  num_train_steps: [100000]
  lr_schedule.value: [2.5e-5]
  max_runtime: [25000]  # ~7 hours per SLURM allocation; requeues before each eval

  collect.env_num: [8]
  collect.eval_env_num: [8]
  # Two evals: at steps 49999 (~end of round 5) and 99998 (~end of round 10).
  collect.eval_interval: [49999]
  !!python/tuple [collect.collect_interval, collect.num_rollouts]: [
    [10000, 20],
  ]
  !!python/tuple [collect.domain, collect.tasks, collect.eval_tasks]: [
    [molmo, [
        molmo_138
      ],
      [
        molmo_138,
        molmo_8, molmo_273, molmo_222, molmo_73, molmo_346, molmo_49, molmo_21, molmo_379,
        molmo_140, molmo_356, molmo_345, molmo_155, molmo_357, molmo_163, molmo_208, molmo_226
      ],
    ],
  ]

  collect.store_prefix_rep: [True]

  rl.n_samples: [32]
  rl.awr_loss_weight: [0.0]
  rl.filtered_sft_weight: [1.0]
  rl.policy.update_interval: [100]

  rl.critic.batch_size: [1024]
  rl.critic.inference_start_step: [1]
  rl.critic.pre_training_steps: [0]
  rl.critic.td_weight_schedule.switch_step: [999999]

  !!python/tuple [rl.critic.td_weight_schedule.init_value, rl.critic.td_weight_schedule.end_value, rl.critic.use_distributional_critic, rl.critic.num_value_bins]: [
    [1, 1, False, 1],     # TD (regression)
  ]

  rl.critic.use_bronet: [True]
  rl.critic.bronet_hidden_dim: [1024]

  rl.buffer_capacity: [250000]
  rl.online_ratio: [1.0]
  rl.discount: [0.995]

  seed: [1]
