script: scripts/exp.py
config_name: pi05_molmo_online_filtered_sft
project_name: vla-post-training
group_name: multitask_fsft_molmo_tasks64_seed2_v0
params:
  lr_schedule.value: [2.5e-5]
  num_train_steps: [2_500]
  requeue_before_eval: [True]
  max_runtime: [25200]  # 7 hours
  requeue_before_eval: [True]
  free_buffer_before_eval: [True]

  collect.eval_interval: [2499]  # only eval at start and end
  !!python/tuple [collect.collect_interval, collect.num_rollouts]: [
    [500, 20],
  ]
  !!python/tuple [collect.domain, collect.tasks, collect.eval_tasks]: [
    [molmo, [
        molmo_332, molmo_33, molmo_242, molmo_369, molmo_126, molmo_383, molmo_295, molmo_81,
        molmo_164, molmo_86, molmo_70, molmo_267, molmo_366, molmo_138, molmo_143, molmo_212,
        molmo_18, molmo_292, molmo_48, molmo_185, molmo_24, molmo_62, molmo_377, molmo_78,
        molmo_28, molmo_311, molmo_50, molmo_56, molmo_399, molmo_187, molmo_121, molmo_27,
        molmo_309, molmo_227, molmo_265, molmo_325, molmo_277, molmo_127, molmo_254, molmo_166, 
        molmo_11, molmo_361, molmo_103, molmo_4, molmo_260, molmo_221, molmo_348, molmo_305, 
        molmo_22, molmo_210, molmo_176, molmo_373, molmo_93, molmo_394, molmo_6, molmo_47, 
        molmo_19, molmo_296, molmo_82, molmo_39, molmo_162, molmo_148, molmo_150, molmo_7
      ],
      [
        molmo_332, molmo_33, molmo_242, molmo_369, molmo_126, molmo_383, molmo_295, molmo_81,
        molmo_164, molmo_86, molmo_70, molmo_267, molmo_366, molmo_138, molmo_143, molmo_212,
        molmo_18, molmo_292, molmo_48, molmo_185, molmo_24, molmo_62, molmo_377, molmo_78,
        molmo_28, molmo_311, molmo_50, molmo_56, molmo_399, molmo_187, molmo_121, molmo_27,
        molmo_309, molmo_227, molmo_265, molmo_325, molmo_277, molmo_127, molmo_254, molmo_166, 
        molmo_11, molmo_361, molmo_103, molmo_4, molmo_260, molmo_221, molmo_348, molmo_305, 
        molmo_22, molmo_210, molmo_176, molmo_373, molmo_93, molmo_394, molmo_6, molmo_47, 
        molmo_19, molmo_296, molmo_82, molmo_39, molmo_162, molmo_148, molmo_150, molmo_7,
        molmo_8, molmo_273, molmo_222, molmo_73, molmo_346, molmo_49, molmo_21, molmo_379,
        molmo_140, molmo_356, molmo_345, molmo_155, molmo_357, molmo_163, molmo_208, molmo_226
      ],
    ],
  ]

  rl.buffer_capacity: [500000]
  rl.online_ratio: [1.0]

  seed: [2]