script: scripts/exp.py
config_name: pi05_libero_online_best_of_n
project_name: vla-post-training
group_name: bofn_libero_tasks1-4_libero_v0
params:
  log_interval: [25]
  num_train_steps: [100000]
  
  collect.env_num: [8]
  collect.eval_env_num: [8]
  collect.eval_interval: [99999]
  !!python/tuple [collect.collect_interval, collect.num_rollouts]: [
    [10000, 20],
  ]
  !!python/tuple [collect.domain, collect.tasks, collect.eval_tasks]: [
    [libero, libero_90_82, [
        libero_90_82,
    ]],
    [libero, [
        libero_90_79, libero_90_31, libero_90_82, libero_90_38,
      ],
      [
        libero_90_79, libero_90_31, libero_90_82, libero_90_38,
    ]]
  ]

  collect.store_prefix_rep: [True]

  rl.critic.batch_size: [1024]
  rl.critic.inference_start_step: [1]   # To speed up data collection at step 0
  rl.critic.pre_training_steps: [0]
  rl.critic.td_weight_schedule.switch_step: [999999]  # No switch
  # TODO: Take the better one from the ../1_mc_vs_td_regression_vs_distributional/bofn_libero_tasks1-4_v0.yaml sweep
  !!python/tuple [rl.critic.td_weight_schedule.init_value, rl.critic.td_weight_schedule.end_value, rl.critic.use_distributional_critic, rl.critic.num_value_bins]: [
    [0, 0, False, 1],     # MC (regression)
    [1, 1, False, 1],     # TD (regression)
    [1, 1, True,  101],   # TD (C51, 101 bins)
  ]

  rl.critic.use_bronet: [False]   # We ran True already

  rl.buffer_capacity: [500000]
  rl.online_ratio: [1.0]

  seed: [0, 1, 2]
