script: scripts/exp.py
config_name: pi05_libero_online_filtered_sft
project_name: vla-post-training
group_name: fsft_multitask_libero_v0
params:
  lr_schedule.value: [5e-5]  # TODO: update
  num_train_steps: [10_000]
  overwrite: [True]

  collect.eval_interval: [9999]  # only eval at start and end
  collect.num_initial_rollouts: [5]
  !!python/tuple [collect.collect_interval, collect.num_rollouts]: [
    [200, 5],  # TODO: tune, choose whether batched
  ]
  !!python/tuple [collect.domain, collect.tasks, collect.eval_tasks]: [
    [libero, libero_90_79, libero_90_79],
    [libero, libero_90_31, libero_90_31],
    [libero, libero_90_82, libero_90_82],
    [libero, libero_90_26, libero_90_26],
    [libero, [
        libero_90_79, libero_90_31, libero_90_82, libero_90_26,
      ],
      [
        libero_90_79, libero_90_31, libero_90_82, libero_90_26,
      ],
    ],
    [libero, [
        libero_90_79, libero_90_31, libero_90_82, libero_90_26, libero_90_5, libero_90_37, libero_90_41, libero_90_65,
        libero_90_11, libero_90_58, libero_90_27, libero_90_7, libero_90_28, libero_90_77, libero_90_9, libero_90_24,
      ],
      [
        libero_90_79, libero_90_31, libero_90_82, libero_90_26, libero_90_5, libero_90_37, libero_90_41, libero_90_65,
        libero_90_11, libero_90_58, libero_90_27, libero_90_7, libero_90_28, libero_90_77, libero_90_9, libero_90_24,
      ]
    ],
    [libero, [
        libero_90_79, libero_90_31, libero_90_82, libero_90_26, libero_90_5, libero_90_37, libero_90_41, libero_90_65,
        libero_90_11, libero_90_58, libero_90_27, libero_90_7, libero_90_28, libero_90_77, libero_90_9, libero_90_24,
        libero_90_32, libero_90_6, libero_90_34, libero_90_36, libero_90_74, libero_90_39, libero_90_4, libero_90_76,
        libero_90_45, libero_90_71, libero_90_89, libero_90_66, libero_90_62, libero_90_78, libero_90_75, librero_90_1,
        libero_90_16, libero_90_17, libero_90_18, libero_90_87, libero_90_21, libero_90_23, libero_90_83, libero_90_80,
        libero_90_85, libero_90_10, libero_90_35, libero_90_69, libero_90_13, libero_90_63, libero_90_14, libero_90_44,
        libero_90_59, libero_90_60, libero_90_12, libero_90_29, libero_90_54, libero_90_33, libero_90_19, libero_90_22,
        libero_90_2, libero_90_50, libero_90_51, libero_90_68, libero_90_20, libero_90_55, libero_90_61, libero_90_57,
      ],
      [
        libero_90_79, libero_90_31, libero_90_82, libero_90_26, libero_90_5, libero_90_37, libero_90_41, libero_90_65,
        libero_90_11, libero_90_58, libero_90_27, libero_90_7, libero_90_28, libero_90_77, libero_90_9, libero_90_24,
        libero_90_32, libero_90_6, libero_90_34, libero_90_36, libero_90_74, libero_90_39, libero_90_4, libero_90_76,
        libero_90_45, libero_90_71, libero_90_89, libero_90_66, libero_90_62, libero_90_78, libero_90_75, librero_90_1,
        libero_90_16, libero_90_17, libero_90_18, libero_90_87, libero_90_21, libero_90_23, libero_90_83, libero_90_80,
        libero_90_85, libero_90_10, libero_90_35, libero_90_69, libero_90_13, libero_90_63, libero_90_14, libero_90_44,
        libero_90_59, libero_90_60, libero_90_12, libero_90_29, libero_90_54, libero_90_33, libero_90_19, libero_90_22,
        libero_90_2, libero_90_50, libero_90_51, libero_90_68, libero_90_20, libero_90_55, libero_90_61, libero_90_57,
      ],
    ]
  ]

  rl.buffer_capacity: [500000]
  rl.online_ratio: [1.0]
  rl.policy.training_start_step: [200]

  seed: [0, 1]